### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by nicoespeon** [nicoespeon/gitgraph.js#48]
List of things to add:

- [x] `commit:mouseover` event when hovering a commit, with a bunch of data (author, message, date, sha1) (see #39)
- [x] Tag system (see #59)
- [x] Displaying branch names (see #66)
- [x] Enable to specify the column index of a branch
- [x] `onClick` on commits (see #76)
- [x] `tooltipHTMLFormatter` for templates

**Comment by nicoespeon** [comment]
Done, will be released with v1.1.0
